# Generated by Django 6.0.1 on 2026-02-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_alter_bill_created_by_alter_payment_processed_by'),
        ('labs', '__first__'),
        ('patients', '0003_ward_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lab_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='labs.labrequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cashier.bill'),
        ),
    ]
