# Generated by Django 6.0.1 on 2026-02-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_payment_lab_request_payment_patient_and_more'),
        ('doctors', '0003_alter_doctor_options_alter_prescription_options_and_more'),
        ('patients', '0004_remove_admission_bed_remove_admission_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_requests', models.ManyToManyField(blank=True, to='doctors.labrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescriptions', models.ManyToManyField(blank=True, to='doctors.prescription')),
            ],
        ),
    ]
