# Generated by Django 6.0.1 on 2026-01-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('Maternity', 'Maternity'), ('Pediatric', 'Pediatric')], max_length=50)),
                ('capacity', models.IntegerField(default=10)),
                ('occupied_beds', models.IntegerField(default=0)),
            ],
        ),
    ]
