# Generated by Django 6.0.1 on 2026-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_labrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('min_threshold', models.PositiveIntegerField(default=10)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='labrequest',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Reason for test / symptoms (entered by Doctor)'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('emergency', 'Emergency (STAT)')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
