# Generated by Django 6.0.1 on 2026-02-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_ward_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='test_results',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='bp',
            field=models.CharField(blank=True, help_text='e.g. 120/80', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='patients.appointment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ordered_tests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medicines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='requires_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text="Patient's primary complaint", null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting Vitals (OPD)'), ('ready', 'Vitals Taken (Ready for MD)'), ('consulting', 'In Consultation'), ('lab_pending', 'Awaiting Lab Results'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
