# Generated by Django 6.0.1 on 2026-02-02 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_medicalrecord_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='in Celsius', max_digits=4)),
                ('bp', models.CharField(help_text='e.g. 120/80', max_length=20)),
                ('pulse', models.PositiveIntegerField(help_text='bpm')),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
        ),
    ]
