# Generated by Django 6.0.1 on 2026-02-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0003_ward_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Chief complaint and clinical findings')),
                ('clinical_notes', models.TextField(blank=True, help_text='Internal notes for other doctors/staff', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispensing'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_issued', to='doctors.doctor')),
                ('doctor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g. 500mg or 5ml', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. 2 times daily (BD)', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 7 days', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total units to dispense')),
                ('instructions', models.CharField(blank=True, help_text='e.g. Before food', max_length=255, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='doctors.prescription')),
            ],
        ),
    ]
