# Generated by Django 6.0.1 on 2026-02-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_prescription_prescriptionitem'),
        ('patients', '0004_remove_admission_bed_remove_admission_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_user',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_link', to='patients.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('results', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('lab_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_labs', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.medicalrecord')),
            ],
        ),
    ]
