# Generated by Django 6.0.1 on 2026-02-02 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0003_alter_doctor_options_alter_prescription_options_and_more'),
        ('patients', '0004_remove_admission_bed_remove_admission_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('clinical_notes', models.TextField()),
                ('ordered_tests', models.BooleanField(default=False)),
                ('prescribed_medicines', models.BooleanField(default=False)),
                ('requires_admission', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='patients.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='doctors.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medical_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_link', to='doctors.medicalrecord'),
        ),
    ]
