# Generated by Django 6.0.1 on 2026-02-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='HMS Core International', max_length=200)),
                ('support_email', models.EmailField(default='admin@hms-core.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('night_mode', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
